Fix some issues with config loading...
kubernetes-client/typescript pull request #10
Opened 2017-07-06 05:50 UTC by brendandburns

@arschles this fixes config loading for credential based configurations.

2017-07-11 23:09 UTC, arschles requested changes
I forgot to submit my review with "Request changes" selected. Only one [comment](https://github.com/kubernetes-client/typescript/pull/10/files#r125941845), and then good to go. Ping me when you're ready for a re-review

2017-07-12 13:53 UTC, brendandburns commented on config.ts
>          }
done.

2017-07-12 13:53 UTC, brendandburns commented
@arschles comments addressed, please re-check.

Thanks!

2017-07-12 16:06 UTC, arschles approved these changes
LGTM, thanks @brendandburns

2017-07-12 16:06 UTC, merged